name: C# CI with .NET cli

on:
  push:
    branches: [ "main" ]
    paths:
       - 'csharp/**'
  pull_request:
    branches: [ "main" ]
    paths:
       - 'csharp/**'
env:
   # Path to the solution file relative to the root of the project.
   FILE_PATH: csharp
   
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.FILE_PATH}}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.FILE_PATH}}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.FILE_PATH}}
